name: Workflow pour les jeux vidéo
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install dependecies
        run: npm install

      - name: Lint code
        run: npx eslint .

      - name: Run test unitaires
        run: npm run test -- --reporter=github-actions

      - name: Créer un résumé de test
        if: always()
        run: |
          echo "Exécution des tests en cours..." >> $GITHUB_STEP_SUMMARY
          echo "Si le test Playwright échoue, une annotation devrait apparaître !" >> $GITHUB_STEP_SUMMARY

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: run test Fonctionelle
        run: npx playwright test e2e/

      - name: Résumé des tests fonctionnels
        if: always()
        run: |
          echo " Tests Fonctionnels (Playwright)" >> $GITHUB_STEP_SUMMARY
          echo "Phase de tests fonctionnels terminée." >> $GITHUB_STEP_SUMMARY

      - name: Audit de dépendances
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Build  
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      actions: read  

    steps:
      - name: Configurer Pages
        uses: actions/configure-pages@v4

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4