name: Workflow pour les jeux vidéo
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Run checkout code 
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
    
    - name: Install dependecies
      run: npm install
    
    - name: Lint code 
      run: npx eslint


    - name: Run test unitaires
      run: npm run test -- --reporter=github-actions 
   
    - name: Créer un résumé de test
      if: always() # Toujours exécuter  même si les tests échouent
      run: |
        echo "Exécution des tests en cours..." >> $GITHUB_STEP_SUMMARY
        echo "Si le test Playwright échoue, une annotation devrait apparaître !" >> $GITHUB_STEP_SUMMARY
      
      # reporter permet de faire le resumé des tests dans le workflow
      #installation des navigateurs playrwright (important)
    
    - name: install playwright browsers
      run: npx playwright install --with-deps
   
    - name: run test Fonctionelle
      run: npx playwright test e2e/
    
    - name: Résumé des tests fonctionnels
      if: always() 
      run: |
          echo " Tests Fonctionnels (Playwright)" >> $GITHUB_STEP_SUMMARY
          echo "Phase de tests fonctionnels terminée." >> $GITHUB_STEP_SUMMARY
    
    - name: Audit de dépendances
      run: npm audit --audit-level=high
      continue-on-error: true